logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    fr.ensaetud.Booking_back: DEBUG

spring:
  profiles:
    active: prod
  application:
    name: booking-back
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: booking
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: booking
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-vfma2hn00fv8i7jg.us.auth0.com/
    client-id: ${AUTH0_CLIENT_ID}
    client-secret: ${AUTH0_CLIENT_SECRET}

application:
  auth0:
    role-landlord-id: rol_8s31PCdujvYD66xs