logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    fr.codecake.airbnbcloneback: INFO

spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: booking
  liquibase:
    contexts: prod
    default-schema: booking
